//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Years.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogArticle
    {
        public string id { get; set; }
        public string submitter { get; set; }
        public string title { get; set; }
        public string category { get; set; }
        public string content { get; set; }
        public int traffic { get; set; }
        public int comment_num { get; set; }
        public System.DateTime update_time { get; set; }
        public System.DateTime create_time { get; set; }
        public string remark { get; set; }
    }
}
