//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db
{
    using System;
    using System.Collections.Generic;
    
    public partial class yao_wan
    {
        public int id { get; set; }
        public string icon { get; set; }
        public string test { get; set; }
        public int num { get; set; }
        public int show { get; set; }
    }
}
